### PR TITLE
Testfiles for test_hpiFit:

### PR DESCRIPTION
**Pull request by RDoerfel**
PR to provide necessary files for test_hpiFit

- .fif: 10.2 second long measurement on vectorview with head movement and continuous hpi

- .txt: position file extracted from maxfilter

### CODE REVIEW

**Review by LorenzE — APPROVED** [review]
Thx @RDoerfel

**Comment by larsoner** [comment]
I'm not aware of what y'all are up to, but FYI I spent a lot of time getting MNE-Python's cHPI fitting code to do close to the same thing as Maxwell filter, and the results are here in case you're trying to do something similar:

https://github.com/mne-tools/mne-python/pull/7290

**Comment by RDoerfel** [comment]
Thank you for the link to the PR @larsoner. We are currently implementing continious hpi fitting for real time head monitoring in MNE Scan. 
In your PR I could read that you made some validation. On what data did you test the cHPI fitting? I think this might be interesting for us too.

**Comment by larsoner** [comment]
> In your PR I could read that you made some validation. On what data did you test the cHPI fitting? I think this might be interesting for us too.

I used 398 files that I had access to locally. Unfortunately I'm not allowed to share those data files (unpublished WIP data), though :( I am sure that there are other suitable datasets you could use, though.

**Pull request merged**
